const fixtureUtils = require('../../utils/fixture-utils');
const fixturesData = require('../../fixtures/lease_agreements');
import leaseIndexPage from '../../pom/lease_management/LeasesIndexTestPage';
import loginPage from '../../pom/owner/owner_login_page';
import navBar from '../../pom/navigation/NavBar';
import leaseDetails from '../../pom/lead_Agreement/leaseDetails';
import agreementList from '../../pom/lead_Agreement/AgreementList';
import leaseSpecifics from '../../pom/lead_Agreement/LeaseSpecifics';
import rentDepositFee from '../../pom/lead_Agreement/RentDepositAndFee';
import peoplePage from '../../pom/lead_Agreement/PeoplePage';
import petsPage from '../../pom/lead_Agreement/PetsPage';
import utilitiesPage from '../../pom/lead_Agreement/UtilitiesPage';
import attachmentsPage from '../../pom/lead_Agreement/AttachmentsPage';
import data from '../../fixtures/lease.json';

let ownerFixtures, owner;
const login_Page = new loginPage();
const leases_Index_Page = leaseIndexPage();
const nav_bar = new navBar();
const lease_Details = new leaseDetails();
const agreement_list = new agreementList();
const lease_specifics = new leaseSpecifics();
const rent_deposit_fee = new rentDepositFee();
const people_page = new peoplePage();
const pets_page = new petsPage();
const utilities_page = new utilitiesPage();
const attachments_page = new attachmentsPage();
describe('Lease Management:Add/Remove Lease', () => {
  before(async () => {
    const serverResponse = await fixtureUtils.createFixtures(
      fixturesData.data(),
    );
    ownerFixtures = serverResponse.data;
    console.log(ownerFixtures['owner_1']);
    owner = serverResponse.data['owner_1'];
  });
  beforeEach(() => {
    cy.visit(Cypress.env('TEST_OWNER_URL') + '/auth/login');
    cy.ownerLogout();
    login_Page.emailInput().type(owner.rawData['email']);
    login_Page.passwordInput().type(owner.rawData['password']);
    login_Page.submitBtn().click();
  });
  it('LEASE_AGREEMENTS', () => {
    nav_bar.leases();
    leases_Index_Page.checkTitle();
    lease_Details.openLease();
    lease_Details.createAgreement();
    agreement_list.leaseSpecificsStartBtn();
    lease_specifics.leaseSpecificsHeader();
    lease_specifics.lease_end_action_continue();
    lease_specifics.saveBtn();
    agreement_list.rentStartBtn();
    rent_deposit_fee.rentHeader();
    rent_deposit_fee.petFee();
    rent_deposit_fee.proratedRentFee();
    rent_deposit_fee.petDepositFee();
    rent_deposit_fee.oneTimeFee();
    rent_deposit_fee.inputPayment();
    rent_deposit_fee.saveBtn();
    agreement_list.peopleStartsBtn();
    people_page.peopleHeader();
    people_page.searchName();
    people_page.selectTenant();
    people_page.additionalOccupants();
    people_page.streetAddressInput().type(data.address);
    people_page.cityInput().type(data.city);
    people_page.stateInput().select(data.state);
    people_page.zipInput().type(data.zip);
    people_page.saveBtn();
    agreement_list.petsStartBtn();
    pets_page.petsHeader();
    pets_page.petsChoice();
    pets_page.saveBtn();
    agreement_list.utilitiesStartBtn();
    utilities_page.utilitiesHeader();
    utilities_page.keysCopy();
    utilities_page.saveBtn();
    agreement_list.provisionsStartBtn();
    attachments_page.attachmentsHeader();
    attachments_page.disclosure();
    attachments_page.saveBtn();
    agreement_list.reviewAndPay();
    agreement_list.finalize();
    agreement_list.payment();
    agreement_list.pay();
    agreement_list.verifyPay();
  });
});
